# Generated by Django 5.2.4 on 2025-11-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('experience_years', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='veterinarians/')),
            ],
            options={
                'verbose_name': 'Veterinarian',
                'verbose_name_plural': 'Veterinarians',
            },
        ),
    ]
