# Generated by Django 5.2.4 on 2025-11-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0002_veterinarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregator',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
