# Generated by Django 5.2.4 on 2025-11-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0003_aggregator_website_equipment_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
