# Generated by Django 5.2.4 on 2025-11-14 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0004_alter_equipment_rental_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
