# Generated by Django 5.2.4 on 2025-11-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0005_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalfeed',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
