# Generated by Django 5.2.4 on 2025-11-14 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0006_animalfeed_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalfeed',
            name='price',
        ),
        migrations.RemoveField(
            model_name='animalfeed',
            name='type',
        ),
    ]
